/*Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
import java.util.Arrays;

public class FindDifference {
    public static char find(String a, String b) {
        char[] charA = a.toCharArray();
        char[] charB = b.toCharArray();
        Arrays.sort(charA);
        Arrays.sort(charB);
        char d = '.';
        for(int i=0;i<charA.length;i++){
            if(charA[i] != charB[i]){
                d = charB[i];
            }
        }
        if(d == '.'){
            return charB[charB.length-1];
        }else{
            return d;
        }
    }
    public static void main(String[] args){
        String s1 = "abcd";
        String s2 = "acdeb";
        System.out.println(find(s1, s2));
    }
}
